# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-23 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20181023_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='publisher',
            field=models.ManyToManyField(to='index.Publisher', verbose_name='签约出版社'),
        ),
    ]
