# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-23 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20181023_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='index.Author', verbose_name='作者'),
        ),
    ]
