# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-28 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20180228_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='picture',
            field=models.ImageField(null=True, upload_to='static/upload/usrimg'),
        ),
    ]
