# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-01 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_auto_20180301_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='index.Author', verbose_name='作者'),
        ),
    ]
