# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-01 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='类型名称')),
                ('desc', models.TextField(null=True, verbose_name='类型描述')),
                ('picture', models.ImageField(upload_to='static/upload/goodstype', verbose_name='类型图片')),
            ],
            options={
                'db_table': 'goodstype',
                'verbose_name': '商品类型',
                'verbose_name_plural': '商品类型',
            },
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterField(
            model_name='users',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='users',
            name='uemail',
            field=models.EmailField(max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='users',
            name='uname',
            field=models.CharField(max_length=20, null=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='users',
            name='upass',
            field=models.CharField(max_length=50, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='users',
            name='uphone',
            field=models.CharField(max_length=20, verbose_name='联系方式'),
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
